CREATE TABLE IF NOT EXISTS  "sectors" (
  "ID"        INTEGER PRIMARY KEY AUTOINCREMENT,
  "X"         INTEGER,
  "Y"         INTEGER);
CREATE TABLE IF NOT EXISTS  "factions" (
  "ID"        INTEGER PRIMARY KEY AUTOINCREMENT,
  "NAME"      TEXT,
  "KIND"      INTEGER,
  "FACTIONID" INTEGER,
  "STEAM64ID" TEXT);
CREATE TABLE IF NOT EXISTS "jumps" (
  "ID"        INTEGER PRIMARY KEY AUTOINCREMENT,
  "TIME"      REAL,
  "KIND"      INTEGER
  "SHIPNAME"  TEXT,
  "SECTORID"  INTEGER,
  "FACTIONID" INTEGER);
CREATE TABLE IF NOT EXISTS "integrations" (
  "ID"        INTEGER PRIMARY KEY AUTOINCREMENT,
  "FACTIONID" INTEGER,
  "DISCORDID" TEXT);
CREATE TABLE IF NOT EXISTS "playerlogins" (
  "ID"        INTEGER PRIMARY KEY AUTOINCREMENT,
  "TIME"      REAL,
  "STEAM64ID" TEXT);